[package]
name = "tinymist"
description = "Fast lsp implementation for typst."
categories = ["compilers", "command-line-utilities"]
keywords = ["cli", "lsp", "language", "typst"]
authors.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]

tinymist-query = { path = "../tinymist-query" }

once_cell.workspace = true
anyhow.workspace = true
comemo.workspace = true
tokio.workspace = true
futures.workspace = true
itertools.workspace = true
async-trait.workspace = true
env_logger.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
parking_lot.workspace = true

typst.workspace = true
typst-pdf.workspace = true
typst-assets = { workspace = true, features = ["fonts"] }

typst-ts-core = { version = "0.4.2-rc6", default-features = false, features = [
    "flat-vector",
    "vector-bbox",
    "no-content-hint",
] }
typst-ts-compiler.workspace = true
typst-preview.workspace = true

tower-lsp.workspace = true

# [lints]
# workspace = true
